### PR TITLE
Trying to clean up the code a little and make it more efficient/easier to read

### PR DESCRIPTION
**Pull request by brick-24**
Hi, this is a great first project I have just modified some code and made basic changes to make it easier to read and add other features for others.

### CODE REVIEW

**Comment by brick-24** [comment]
@ryanm-10

**Comment by ryanm-10** [comment]
@COMMANDO2406 thank u for the help!

**Comment by ryanm-10** [comment]
@COMMANDO2406 I was about to update my project for the calculator, I wanted to keep the while loop and I saw if I enter a word for the first or second value I get an error and i want it to return 'invalid input' can you check it out in a minute to see if the updated code makes sense?

**Comment by brick-24** [comment]
I guess you can add an if statement which checks if the entered value is an integer or a float value

**Comment by brick-24** [comment]
I can look at it by tomorrow if that's ok?

**Pull request closed without merging**
